package it.unicam.cs.mpmgc.vectorrally.api.model.algorithms;

import it.unicam.cs.mpmgc.vectorrally.api.model.movements.Acceleration;
import it.unicam.cs.mpmgc.vectorrally.api.model.movements.Vector;

import java.util.ArrayList;
import java.util.List;

/**
 * Defines a method for generating possible shifts ({@link Vector} objects) from a given speed.
 *
 * @version 1.0
 * @since 2024-07-11
 * @author Marta Musso
 * <a href="mailto:marta.musso@studenti.unicam.it">marta.musso@studenti.unicam.it</a>
 */
public interface NeighborsGenerator {

    /**
     * Generates all possible shifts (accelerations) from the given speed.
     *
     * @param speed the current {@link Vector} as an acceleration vector.
     * @return a {@link List} of possible new {@link Vector} objects representing the shifts.
     */
    List<Vector> generateShifts(Vector speed);

    /**
     * Generates a list of new accelerations by applying given delta values to the current speed.
     *
     * @param speed the current {@link Vector} as an acceleration vector.
     * @param dx an array of x-axis delta values to be applied to the current speed.
     * @param dy an array of y-axis delta values to be applied to the current speed.
     * @return a {@link List} of new {@link Vector} objects generated by applying the given delta values.
     */
    default List<Vector> getAccelerations(Vector speed, int[] dx, int[] dy) {
        List<Vector> shifts = new ArrayList<>();
        for (int i = 0; i < dx.length; i++) {
            shifts.add(new Acceleration(speed.getDx() + dx[i], speed.getDy() + dy[i]));
        }
        return shifts;
    }
}
