/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpmgc.vectorrally.app;

public class App {
    public static void main(String[] args) {
        System.out.println("Ciao mondo!");
    }
}
