/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpmgc.vectorrally.app;


import com.sun.tools.javac.Main;
import it.unicam.cs.mpmgc.vectorrally.api.controller.match.BasicGameEngine;
import it.unicam.cs.mpmgc.vectorrally.api.view.*;

import it.unicam.cs.mpmgc.vectorrally.api.controller.match.GameEngine;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class is responsible for starting the terminal application.
 *
 * @version 1.0
 * @since 2024-07-17
 * @author Marta Musso
 * <a href="mailto:marta.musso@studenti.unicam.it">marta.musso@studenti.unicam.it</a>
 */
public class TerminalApp {
    private static final Logger logger = Logger.getLogger(Main.class.getName());
    public static void main(String[] args) {
        try {
            IOController ioController = new TerminalIOController();
            MatchGameView matchGameView = new CLIMatchGameView(ioController);
            SetupGameView setupGameView = new CLISetupGameView(ioController);
            FinishGameView finishGameView = new CLIFinishGameView(ioController);
            GameEngine gameController = new BasicGameEngine(matchGameView, finishGameView, setupGameView);
            ioController.displayWelcome();
            if(ioController.getAskIfPlayerIgnoresRules()) ioController.displayGameRules();
            gameController.startGame();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "An error occurred while starting the game", e);
        }
    }
}
